// Command htmlskeleton turns a real HTML page into a structure-only fixture
// for pagewatch golden tests: every text node is replaced character-class by
// character-class (hiragana -> あ, katakana -> ア, kanji -> 亜, latin lower ->
// a, latin upper -> A, digit -> 0; symbols and whitespace pass through
// unchanged), while tags, attributes, and nesting are left untouched. See
// docs/feedless-site-subscription-pagewatch.md §14.5 for the design and the
// reasoning: real page content must never be committed to this repository.
//
// This is a standalone dev tool; it is not part of the feedla binary.
//
// Usage:
//
//	go run ./tools/htmlskeleton -in saved.html -out testdata/diary-v1.html \
//	    -source https://example.net/memo/ -keep '^Last Modified:'
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"
	"time"
	"unicode"

	"golang.org/x/net/html"
)

type regexpList []*regexp.Regexp

func (l *regexpList) String() string { return "" }

func (l *regexpList) Set(v string) error {
	re, err := regexp.Compile(v)
	if err != nil {
		return fmt.Errorf("invalid -keep regexp %q: %w", v, err)
	}
	*l = append(*l, re)
	return nil
}

func main() {
	var in, out, source string
	var keep regexpList
	flag.StringVar(&in, "in", "", "input HTML file (a real, saved page; never committed)")
	flag.StringVar(&out, "out", "", "output HTML file (the anonymized fixture)")
	flag.StringVar(&source, "source", "", "source URL, recorded in the generated header comment")
	flag.Var(&keep, "keep", "regexp matching text nodes to leave unmodified (repeatable)")
	flag.Parse()

	if in == "" || out == "" {
		fmt.Fprintln(os.Stderr, "usage: htmlskeleton -in <file> -out <file> [-source <url>] [-keep <regexp>]...")
		os.Exit(2)
	}

	if err := run(in, out, source, keep); err != nil {
		fmt.Fprintln(os.Stderr, "htmlskeleton:", err)
		os.Exit(1)
	}
}

func run(in, out, source string, keep regexpList) error {
	data, err := os.ReadFile(in)
	if err != nil {
		return fmt.Errorf("read %s: %w", in, err)
	}

	doc, err := html.Parse(bytes.NewReader(data))
	if err != nil {
		return fmt.Errorf("parse %s: %w", in, err)
	}

	anonymize(doc, keep)

	var buf bytes.Buffer
	buf.WriteString(headerComment(source, keep))
	if err := html.Render(&buf, doc); err != nil {
		return fmt.Errorf("render: %w", err)
	}

	if err := os.WriteFile(out, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", out, err)
	}
	return nil
}

// anonymize mutates the tree in place: text nodes are transliterated
// character-class by character-class (unless a -keep pattern matches the
// whole node), and comment nodes are emptied. Element tags and attributes
// (class/id/name/role/href/src/...) are left exactly as parsed, since the
// noise- and attribute-filtering rules under test key off of them.
func anonymize(n *html.Node, keep regexpList) {
	switch n.Type {
	case html.TextNode:
		n.Data = anonymizeText(n.Data, keep)
	case html.CommentNode:
		n.Data = ""
	}
	for c := n.FirstChild; c != nil; c = c.NextSibling {
		anonymize(c, keep)
	}
}

func anonymizeText(s string, keep regexpList) string {
	for _, re := range keep {
		if re.MatchString(s) {
			return s
		}
	}
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		b.WriteRune(anonymizeRune(r))
	}
	return b.String()
}

func anonymizeRune(r rune) rune {
	switch {
	case unicode.Is(unicode.Hiragana, r):
		return 'あ'
	case unicode.Is(unicode.Katakana, r):
		return 'ア'
	case unicode.Is(unicode.Han, r):
		return '亜'
	case r >= 'a' && r <= 'z':
		return 'a'
	case r >= 'A' && r <= 'Z':
		return 'A'
	case r >= '0' && r <= '9':
		return '0'
	default:
		return r
	}
}

func headerComment(source string, keep regexpList) string {
	if source == "" {
		source = "(unspecified)"
	}
	keptStr := "(none)"
	if len(keep) > 0 {
		parts := make([]string, len(keep))
		for i, re := range keep {
			parts[i] = re.String()
		}
		keptStr = strings.Join(parts, ", ")
	}
	return fmt.Sprintf(
		"<!-- generated by tools/htmlskeleton from %s on %s\n"+
			"     structure only: all text has been replaced. -keep: %s -->\n",
		source, time.Now().UTC().Format("2006-01-02"), keptStr,
	)
}
